version: 1
directus: 11.13.1
vendor: postgres
collections:
  - collection: Giramelle_Streams
    meta:
      accountability: all
      archive_app_filter: true
      archive_field: status
      archive_value: archived
      collapse: open
      collection: Giramelle_Streams
      color: null
      display_template: null
      group: null
      hidden: false
      icon: null
      item_duplication_fields: null
      note: null
      preview_url: null
      singleton: false
      sort: null
      sort_field: null
      translations: null
      unarchive_value: draft
      versioning: false
    schema:
      name: Giramelle_Streams
fields:
  - collection: Giramelle_Streams
    field: id
    type: integer
    meta:
      collection: Giramelle_Streams
      conditions: null
      display: null
      display_options: null
      field: id
      group: null
      hidden: true
      interface: input
      note: null
      options: null
      readonly: true
      required: false
      searchable: true
      sort: 1
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      name: id
      table: Giramelle_Streams
      data_type: integer
      default_value: nextval('"Giramelle_Streams_id_seq"'::regclass)
      max_length: null
      numeric_precision: 32
      numeric_scale: 0
      is_nullable: false
      is_unique: true
      is_indexed: false
      is_primary_key: true
      is_generated: false
      generation_expression: null
      has_auto_increment: true
      foreign_key_table: null
      foreign_key_column: null
  - collection: Giramelle_Streams
    field: status
    type: string
    meta:
      collection: Giramelle_Streams
      conditions: null
      display: labels
      display_options:
        choices:
          - background: var(--theme--primary-background)
            color: var(--theme--primary)
            foreground: var(--theme--primary)
            text: $t:published
            value: published
          - background: var(--theme--background-normal)
            color: var(--theme--foreground)
            foreground: var(--theme--foreground)
            text: $t:draft
            value: draft
          - background: var(--theme--warning-background)
            color: var(--theme--warning)
            foreground: var(--theme--warning)
            text: $t:archived
            value: archived
        showAsDot: true
      field: status
      group: null
      hidden: false
      interface: select-dropdown
      note: null
      options:
        choices:
          - color: var(--theme--primary)
            text: $t:published
            value: published
          - color: var(--theme--foreground)
            text: $t:draft
            value: draft
          - color: var(--theme--warning)
            text: $t:archived
            value: archived
      readonly: false
      required: false
      searchable: true
      sort: 2
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      name: status
      table: Giramelle_Streams
      data_type: character varying
      default_value: draft
      max_length: 255
      numeric_precision: null
      numeric_scale: null
      is_nullable: false
      is_unique: false
      is_indexed: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: null
      foreign_key_column: null
  - collection: Giramelle_Streams
    field: user_created
    type: uuid
    meta:
      collection: Giramelle_Streams
      conditions: null
      display: user
      display_options: null
      field: user_created
      group: null
      hidden: true
      interface: select-dropdown-m2o
      note: null
      options:
        template: '{{avatar}} {{first_name}} {{last_name}}'
      readonly: true
      required: false
      searchable: true
      sort: 3
      special:
        - user-created
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      name: user_created
      table: Giramelle_Streams
      data_type: uuid
      default_value: null
      max_length: null
      numeric_precision: null
      numeric_scale: null
      is_nullable: true
      is_unique: false
      is_indexed: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: directus_users
      foreign_key_column: id
  - collection: Giramelle_Streams
    field: date_created
    type: timestamp
    meta:
      collection: Giramelle_Streams
      conditions: null
      display: datetime
      display_options:
        relative: true
      field: date_created
      group: null
      hidden: true
      interface: datetime
      note: null
      options: null
      readonly: true
      required: false
      searchable: true
      sort: 4
      special:
        - date-created
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      name: date_created
      table: Giramelle_Streams
      data_type: timestamp with time zone
      default_value: null
      max_length: null
      numeric_precision: null
      numeric_scale: null
      is_nullable: true
      is_unique: false
      is_indexed: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: null
      foreign_key_column: null
  - collection: Giramelle_Streams
    field: date_updated
    type: timestamp
    meta:
      collection: Giramelle_Streams
      conditions: null
      display: datetime
      display_options:
        relative: true
      field: date_updated
      group: null
      hidden: true
      interface: datetime
      note: null
      options: null
      readonly: true
      required: false
      searchable: true
      sort: 5
      special:
        - date-updated
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      name: date_updated
      table: Giramelle_Streams
      data_type: timestamp with time zone
      default_value: null
      max_length: null
      numeric_precision: null
      numeric_scale: null
      is_nullable: true
      is_unique: false
      is_indexed: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: null
      foreign_key_column: null
  - collection: Giramelle_Streams
    field: Stream_Key
    type: string
    meta:
      collection: Giramelle_Streams
      conditions: null
      display: null
      display_options: null
      field: Stream_Key
      group: null
      hidden: false
      interface: input
      note: null
      options: null
      readonly: false
      required: false
      searchable: true
      sort: 6
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      name: Stream_Key
      table: Giramelle_Streams
      data_type: character varying
      default_value: null
      max_length: 255
      numeric_precision: null
      numeric_scale: null
      is_nullable: true
      is_unique: false
      is_indexed: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: null
      foreign_key_column: null
  - collection: Giramelle_Streams
    field: Avatar
    type: uuid
    meta:
      collection: Giramelle_Streams
      conditions: null
      display: null
      display_options: null
      field: Avatar
      group: null
      hidden: false
      interface: file-image
      note: null
      options: null
      readonly: false
      required: false
      searchable: true
      sort: 8
      special:
        - file
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      name: Avatar
      table: Giramelle_Streams
      data_type: uuid
      default_value: null
      max_length: null
      numeric_precision: null
      numeric_scale: null
      is_nullable: true
      is_unique: false
      is_indexed: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: directus_files
      foreign_key_column: id
  - collection: Giramelle_Streams
    field: URL
    type: string
    meta:
      collection: Giramelle_Streams
      conditions: null
      display: null
      display_options: null
      field: URL
      group: null
      hidden: false
      interface: input
      note: null
      options: null
      readonly: false
      required: false
      searchable: true
      sort: 9
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      name: URL
      table: Giramelle_Streams
      data_type: character varying
      default_value: null
      max_length: 255
      numeric_precision: null
      numeric_scale: null
      is_nullable: true
      is_unique: false
      is_indexed: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: null
      foreign_key_column: null
  - collection: Giramelle_Streams
    field: Status
    type: text
    meta:
      collection: Giramelle_Streams
      conditions: null
      display: null
      display_options: null
      field: Status
      group: null
      hidden: false
      interface: input-multiline
      note: null
      options: null
      readonly: false
      required: false
      searchable: true
      sort: 10
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      name: Status
      table: Giramelle_Streams
      data_type: text
      default_value: null
      max_length: null
      numeric_precision: null
      numeric_scale: null
      is_nullable: true
      is_unique: false
      is_indexed: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: null
      foreign_key_column: null
  - collection: Giramelle_Streams
    field: Language
    type: string
    meta:
      collection: Giramelle_Streams
      conditions: null
      display: null
      display_options: null
      field: Language
      group: null
      hidden: false
      interface: select-dropdown
      note: null
      options:
        choices:
          - text: English
            value: English
          - text: Portuguese
            value: Portuguese
          - text: Spanish
            value: Spanish
          - text: Chinese
            value: Chinese
          - text: Mexican
            value: Mexican
      readonly: false
      required: true
      searchable: true
      sort: 11
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      name: Language
      table: Giramelle_Streams
      data_type: character varying
      default_value: English
      max_length: 255
      numeric_precision: null
      numeric_scale: null
      is_nullable: true
      is_unique: false
      is_indexed: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: null
      foreign_key_column: null
systemFields:
  - collection: directus_activity
    field: timestamp
    schema:
      is_indexed: true
  - collection: directus_revisions
    field: parent
    schema:
      is_indexed: true
relations:
  - collection: Giramelle_Streams
    field: user_created
    related_collection: directus_users
    meta:
      junction_field: null
      many_collection: Giramelle_Streams
      many_field: user_created
      one_allowed_collections: null
      one_collection: directus_users
      one_collection_field: null
      one_deselect_action: nullify
      one_field: null
      sort_field: null
    schema:
      table: Giramelle_Streams
      column: user_created
      foreign_key_table: directus_users
      foreign_key_column: id
      constraint_name: giramelle_streams_user_created_foreign
      on_update: NO ACTION
      on_delete: NO ACTION
  - collection: Giramelle_Streams
    field: Avatar
    related_collection: directus_files
    meta:
      junction_field: null
      many_collection: Giramelle_Streams
      many_field: Avatar
      one_allowed_collections: null
      one_collection: directus_files
      one_collection_field: null
      one_deselect_action: nullify
      one_field: null
      sort_field: null
    schema:
      table: Giramelle_Streams
      column: Avatar
      foreign_key_table: directus_files
      foreign_key_column: id
      constraint_name: giramelle_streams_avatar_foreign
      on_update: NO ACTION
      on_delete: SET NULL